version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0  # Pre-configured OpenJDK 11 with Maven

    steps:
      - checkout  # Checks out the code from your GitHub repository

      - run:
          name: Verify Java and Maven Installation
          command: |
            java -version
            mvn -version

      - run:
          name: Fix Java Certificates
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
            sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure

      - run:
          name: Clean and Reconfigure Packages
          command: |
            sudo apt-get clean
            sudo apt-get update --fix-missing
            sudo dpkg --configure -a
            sudo apt-get install -y --fix-broken

      - run:
          name: Build and Test
          command: mvn clean test

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
