version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0  # Pre-configured OpenJDK 11 with Maven

    steps:
      - checkout  # Checks out the code from your GitHub repository

      - run:
          name: Verify Java and Maven Installation
          command: |
            java -version
            mvn -version
      - run:
          name: Build and Test
          command: mvn clean test
      - run:
          name: Send Slack Notification
          command: |
            if [ $? -eq 0 ]; then
              STATUS_MESSAGE="Build and Tests Passed! 🎉"
              COLOR="good"
            else
              STATUS_MESSAGE="Build or Tests Failed! ❌"
              COLOR="danger"
            fi
            
            curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"attachments\": [
                {
                  \"fallback\": \"CircleCI Build Notification\",
                  \"color\": \"$COLOR\",
                  \"text\": \"$STATUS_MESSAGE\",
                  \"fields\": [
                    { \"title\": \"Project\", \"value\": \"$CIRCLE_PROJECT_REPONAME\", \"short\": true },
                    { \"title\": \"Branch\", \"value\": \"$CIRCLE_BRANCH\", \"short\": true },
                    { \"title\": \"Build URL\", \"value\": \"$CIRCLE_BUILD_URL\", \"short\": false }
                  ]
                }
              ]
            }" $SLACK_WEBHOOK_URL


workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
