version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0  # Pre-configured OpenJDK 11 with Maven

    steps:
      - checkout  # Checks out the code from your GitHub repository

      - run:
          name: Verify Java and Maven Installation
          command: |
            java -version
            mvn -version
      - run:
          name: Build and Test
          command: mvn clean test


workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
