name: TestNG CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Run TestNG Tests
        run: mvn clean test

  notify-success:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()  # Runs only if the previous job succeeds

    steps:
      - name: Send Slack Notification on Success
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"✅ *Build Passed!* \nRepository: *${{ github.repository }}* \nBranch: *${{ github.ref_name }}* \nCommit: *${{ github.sha }}* \nView the build: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          }" ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-failure:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: failure()  # Runs only if the previous job fails

    steps:
      - name: Send Slack Notification on Failure
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"❌ *Build Failed!* \nRepository: *${{ github.repository }}* \nBranch: *${{ github.ref_name }}* \nCommit: *${{ github.sha }}* \nView the build: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          }" ${{ secrets.SLACK_WEBHOOK_URL }}
